---
- name: Change FortiGate hostname
  hosts: fortigate
  gather_facts: false

  tasks:
    - name: Change hostname
      ansible.builtin.raw: |
        config system global
            set hostname FortiGate-dhia
        end
      register: result

    - debug:
        var: result
