---
- name: Test firewall variables
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/firewalls.vars

  tasks:

    - name: Display firewall information
      ansible.builtin.debug:
        msg: "Firewall {{ item.hostname }} - Serial {{ item.serial }}"
      loop: "{{ firewalls }}"
